version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "saas"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tm8ubmqwrwlb"
s3_prefix = "saas"
region = "ap-southeast-3"
capabilities = "CAPABILITY_IAM"
image_repositories = []
